version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: cocopan_postgres
    environment:
      POSTGRES_DB: cocopan_monitor
      POSTGRES_USER: cocopan
      POSTGRES_PASSWORD: cocopan123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cocopan_network
    restart: unless-stopped

  monitor:
    build: .
    container_name: cocopan_monitor
    command: python monitor_service.py
    environment:
      - DATABASE_URL=postgresql://cocopan:cocopan123@postgres:5432/cocopan_monitor
      - TIMEZONE=Asia/Manila
      - LOG_LEVEL=INFO
    volumes:
      - ./branch_urls.json:/app/branch_urls.json:ro
    networks:
      - cocopan_network
    depends_on:
      - postgres
    restart: unless-stopped

  dashboard:
    build: .
    container_name: cocopan_dashboard
    command: streamlit run enhanced_dashboard.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true
    environment:
      - DATABASE_URL=postgresql://cocopan:cocopan123@postgres:5432/cocopan_monitor
      - TIMEZONE=Asia/Manila
    ports:
      - "8501:8501"
    networks:
      - cocopan_network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cocopan_network: